<a href="https://colab.research.google.com/github/pranavsinghpatil/Open-Acumen/blob/main/PyTorch%26Tensorflow_Funds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> *Side-by-side in PyTorch & TensorFlow*

### Creating Tensors

In [1]:
# PyTorch
import torch

x_torch = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print("PyTorch tensor:\n", x_torch)
print("Device:", x_torch.device)


PyTorch tensor:
 tensor([[1., 2.],
        [3., 4.]])
Device: cpu


In [2]:
# TensorFlow
import tensorflow as tf

x_tf = tf.constant([[1.0, 2.0], [3.0, 4.0]])
print("TensorFlow tensor:\n", x_tf)
print("Device:", x_tf.device)  # shows if on CPU/GPU


TensorFlow tensor:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Device: /job:localhost/replica:0/task:0/device:CPU:0


## GPU Availability

In [1]:
import torch

x = torch.tensor([1.0, 2.0, 3.0])
x_gpu = x.to("cuda")   # moves tensor to GPU
print(x_gpu.device)    # shows 'cuda:0'

# In PyTorch: you explicitly move tensors.

cuda:0


In [2]:
import tensorflow as tf

x = tf.constant([1.0, 2.0, 3.0])
print(x.device)  # usually shows GPU if TensorFlow detects one

# TensorFlow: it’s more automatic — TensorFlow will place tensors on GPU if available.

/job:localhost/replica:0/task:0/device:GPU:0


In [3]:
# in Tensorflow - If you want to force a device:

with tf.device("/GPU:0"):
    x_gpu = tf.constant([1.0, 2.0, 3.0])


In [4]:
# On Availability
import torch

# device selection
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# create a tensor on that device
x = torch.tensor([1.0, 2.0, 3.0]).to(device)

print("Using device:", device)
print("Tensor is on:", x.device)

#  --------------------------------------------------------------------
#  In Tf

import tensorflow as tf
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))



Using device: cuda
Tensor is on: cuda:0
Num GPUs Available: 1


# Tensor Operations

In [1]:
#  Creating

# PyTorch
import torch
a = torch.tensor([1, 2, 3], dtype=torch.float32)

# TensorFlow
import tensorflow as tf
b = tf.constant([1, 2, 3], dtype=tf.float32)


In [2]:
# basic math

# PyTorch
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
print(x + y)   # tensor([5, 7, 9])
print(x * y)   # elementwise multiply

# TensorFlow
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
print(x + y)   # tf.Tensor([5 7 9], shape=(3,), dtype=int32)
print(x * y)


tensor([5, 7, 9])
tensor([ 4, 10, 18])
tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [3]:
#  Matrix Multiplication

# PyTorch
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
print(torch.matmul(A, B))   # [[19,22],[43,50]]

# TensorFlow
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])
print(tf.matmul(A, B))


tensor([[19, 22],
        [43, 50]])
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [5]:
# Reshaping

# PyTorch
x = torch.arange(6)         # [0,1,2,3,4,5]
print(x.reshape(2,3))

# TensorFlow
x = tf.range(6)
print(tf.reshape(x, (2,3)))


tensor([[0, 1, 2],
        [3, 4, 5]])
tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [4]:
#  Reduction ops


# PyTorch
x = torch.tensor([1.0, 2.0, 3.0])
print(x.mean())    # 2.0
print(x.sum())     # 6.0

# TensorFlow
x = tf.constant([1.0, 2.0, 3.0])
print(tf.reduce_mean(x))  # 2.0
print(tf.reduce_sum(x))   # 6.0


tensor(2.)
tensor(6.)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


Quick note:

- PyTorch usually uses methods (x.sum(), x.mean())

- TensorFlow usually uses functions (tf.reduce_sum(x), tf.reduce_mean(x))